minimumReleaseAgeExclude:
  - '@next/*'
  - next
overrides:
  baseline-browser-mapping@>=2.0.0 <2.11.0: ^2.11.0
  browserslist@<=4.28.6: ^4.28.7
  nanoid@<3.3.12: ^3.3.12
  nanoid@<3.3.16: ^3.3.16
  nanoid@<3.3.18: ^3.3.18
  postcss@<8.5.10: ^8.5.10
  postcss@<=8.5.11: ^8.5.12
  postcss@<=8.5.17: ^8.5.18
  postcss@<=8.5.22: ^8.5.23
  sharp@<0.35.4: ^0.35.4
